@extends('layout')
@section('title',$document->number)
@section('content')<div class="actions no-print"><a href="{{ route('admin.documents.index',['type'=>$document->type]) }}">← Documents</a>@if($document->status==='draft')<a class="button secondary" href="{{ route('admin.documents.edit',$document) }}">Edit draft</a>@endif<button type="button" id="print-document">Print / Save as PDF</button></div>
<div class="panel no-print"><form class="filters" method="post" action="{{ route('admin.documents.status',$document) }}">@csrf @method('PATCH')<input type="hidden" name="revision" value="{{ $document->revision }}"><label>Status<select name="status">@foreach(\App\Models\BusinessDocument::statuses($document->type) as $s)@continue($document->type==='invoice' && in_array($s,['paid','partially_paid'],true) && $document->status!==$s)<option value="{{ $s }}" @selected($document->status===$s)>{{ ucfirst(str_replace('_',' ',$s)) }}</option>@endforeach</select></label><button>Update status</button></form><p class="muted">Issuing locks the content. Status changes are recorded here; they do not send documents or process payments.</p><div class="actions">@foreach(\App\Models\BusinessDocument::TYPES as $key=>$label)<a href="{{ route('admin.documents.create',['parent'=>$document->id,'type'=>$key]) }}">Create linked {{ strtolower($label) }} ↗</a>@endforeach</div></div>
@if($document->type==='invoice')@include('admin.invoice-payments')@endif
<article class="paper"><div class="document-brand-bar"><img src="{{ asset('brand/assets/bron-logo.png') }}" width="180" height="58" alt="BRON Highworks"></div><div class="document-head"><div><p>316-B, Lorong Kedah, Taman Melawati,<br>53100 Kuala Lumpur, MALAYSIA<br>hello@bronhighworks.com · +60 19-652 2238</p></div><div><h2>{{ \App\Models\BusinessDocument::TYPES[$document->type] }}</h2><strong>{{ $document->number }}</strong><p>{{ strtoupper(str_replace('_',' ',$document->status)) }}<br>Issue date: {{ $document->issued_on->format('d M Y') }}@if($document->due_on)<br>{{ $document->type==='quotation'?'Valid until':'Due / delivery date' }}: {{ $document->due_on->format('d M Y') }}@endif</p></div></div>
<div class="grid"><div><p class="eyebrow">{{ $document->type==='supplier_po'?'SUPPLIER':'CUSTOMER' }}</p><strong>{{ $document->party_name }}</strong><p class="pre">{{ $document->party_address }}</p><p>{{ $document->party_email }}</p></div><div>@if($document->external_reference)<p>External reference: {{ $document->external_reference }}</p>@endif @if($document->parent)<p>Related document: {{ $document->parent->number }}</p>@endif @if($document->visit)<p>Site: {{ $document->visit->address }}</p><a class="no-print" href="{{ route('admin.visits.show',$document->visit) }}">View site visit ↗</a>@endif</div></div>
<div class="table-wrap"><table><thead><tr><th>Description</th><th>Qty</th>@if($document->type!=='delivery_order')<th>Unit price</th><th>Amount (MYR)</th>@endif</tr></thead><tbody>@foreach($document->items as $item)<tr><td>{{ $item['description'] }}</td><td>{{ $item['quantity'] }}</td>@if($document->type!=='delivery_order')<td>{{ number_format((float)$item['unit_price'],2) }}</td><td>{{ number_format($item['total_cents']/100,2) }}</td>@endif</tr>@endforeach</tbody></table></div>
@if($document->type!=='delivery_order')<div class="totals"><p>Subtotal <strong>{{ number_format($document->subtotal_cents/100,2) }}</strong></p><p>Tax ({{ number_format($document->tax_basis_points/100,2) }}%) <strong>{{ number_format($document->tax_cents/100,2) }}</strong></p><h3>Total MYR <strong>{{ number_format($document->total_cents/100,2) }}</strong></h3>@if($document->type==='invoice' && !($document->status==='paid' && $document->payments->isEmpty()))<p>Amount paid <strong>{{ number_format($document->recordedPaidCents()/100,2) }}</strong></p><p>Balance due <strong>{{ number_format($document->balanceCents()/100,2) }}</strong></p>@endif</div>@endif
@if($document->notes)<h3>Notes / terms</h3><p class="pre">{{ $document->notes }}</p>@endif
@if($document->type==='delivery_order')<div class="signature">Received by: ____________________ &nbsp; Date: ______________<br><br>Signature / company stamp: ____________________</div>@endif
</article>@endsection