@extends('layout')
@section('title',($document->exists?'Edit ':'Create ').\App\Models\BusinessDocument::TYPES[$document->type])
@section('content')<form class="panel" method="post" action="{{ $document->exists?route('admin.documents.update',$document):route('admin.documents.store') }}">@csrf @if($document->exists) @method('PUT') @endif
<input type="hidden" name="type" value="{{ $document->type }}"><input type="hidden" name="site_visit_id" value="{{ $document->site_visit_id }}"><input type="hidden" name="parent_id" value="{{ $document->parent_id }}"><input type="hidden" name="revision" value="{{ $document->revision??1 }}">
@if($visit)<p>Site visit: <a href="{{ route('admin.visits.show',$visit) }}">{{ $visit->name }} · {{ $visit->address }}</a></p>@endif
@if($parent)<p>Related document: <a href="{{ route('admin.documents.show',$parent) }}">{{ $parent->number }}</a></p>@endif
<div class="grid"><label>{{ $document->type==='supplier_po'?'Supplier':'Customer' }} name *<input name="party_name" value="{{ old('party_name',$document->party_name) }}" required maxlength="200"></label><label>Email<input type="email" name="party_email" value="{{ old('party_email',$document->party_email) }}"></label><label class="wide">Billing / delivery address *<textarea name="party_address" required>{{ old('party_address',$document->party_address) }}</textarea></label><label>Issue date *<input type="date" name="issued_on" value="{{ old('issued_on',$document->issued_on?->format('Y-m-d')) }}" required></label><label>{{ $document->type==='quotation'?'Valid until':'Due / delivery date' }}<input type="date" name="due_on" value="{{ old('due_on',$document->due_on?->format('Y-m-d')) }}"></label><label class="wide">Customer / supplier reference<input name="external_reference" value="{{ old('external_reference',$document->external_reference) }}" maxlength="200"></label></div>
<h2>{{ $document->type==='delivery_order'?'Delivered items / services':'Line items' }}</h2><p class="muted">Amounts are in MYR. Totals are calculated on save. Delivery orders print quantities without prices.</p>
<div id="items">@foreach(old('items',$document->items?:[['description'=>'','quantity'=>'1','unit_price'=>'0.00']]) as $i=>$item)<div class="item-row"><label>Description *<input name="items[{{ $i }}][description]" value="{{ $item['description'] }}" required maxlength="500"></label><label>Quantity *<input type="number" step="0.01" min="0.01" max="100000" name="items[{{ $i }}][quantity]" value="{{ $item['quantity'] }}" required></label><label>Unit price (MYR)<input type="number" step="0.01" min="0" max="10000000" name="items[{{ $i }}][unit_price]" value="{{ $item['unit_price'] }}" required></label><button type="button" class="outline remove-item" aria-label="Remove this line item">Remove</button></div>@endforeach</div>
<button type="button" id="add-item" class="outline">+ Add line item</button><div class="grid top-gap"><label>Tax (%)<input name="tax_percent" type="number" step="0.01" min="0" max="100" value="{{ old('tax_percent',number_format(($document->tax_basis_points??0)/100,2,'.','')) }}" required><small>Enter only the rate applicable to this transaction.</small></label><label class="wide">Notes / terms<textarea name="notes" maxlength="5000">{{ old('notes',$document->notes) }}</textarea></label></div><button>Save draft</button></form>
<template id="item-template"><div class="item-row"><label>Description *<input data-field="description" required maxlength="500"></label><label>Quantity *<input data-field="quantity" type="number" step="0.01" min="0.01" max="100000" value="1" required></label><label>Unit price (MYR)<input data-field="unit_price" type="number" step="0.01" min="0" max="10000000" value="0.00" required></label><button type="button" class="outline remove-item" aria-label="Remove this line item">Remove</button></div></template>@endsection