@extends('layout')
@section('title','Request a site assessment')
@section('intro')<p>Tell us about your building or solar installation. Our team will contact you to arrange a suitable visit.</p>@endsection
@section('content')
@if(session('reference'))<section class="panel"><p class="eyebrow">REQUEST RECEIVED</p><h2>Thank you. Let’s reach higher.</h2><p>Your reference: <strong>{{ session('reference') }}</strong></p><p>Your preferred date is a request, not a confirmed appointment. BRON will contact you to confirm access and timing.</p><a class="button" href="{{ route('home') }}">Return to BRON</a></section>
@else
<form class="panel" method="post" action="{{ route('assessment.store') }}">@csrf
<h2>Your details</h2><div class="grid"><label>Contact name *<input name="name" autocomplete="name" value="{{ old('name') }}" required maxlength="150"></label><label>Company<input name="company" autocomplete="organization" value="{{ old('company') }}" maxlength="150"></label><label>Email *<input type="email" name="email" autocomplete="email" value="{{ old('email') }}" required maxlength="200"></label><label>Phone / WhatsApp *<input type="tel" name="phone" autocomplete="tel" value="{{ old('phone') }}" required maxlength="50"></label></div>
<h2>The site</h2><div class="grid"><label>Cleaning service *<select name="service" required><option value="">Select a service</option>@foreach(\App\Models\SiteVisit::SERVICES as $s)<option @selected(old('service')===$s)>{{ $s }}</option>@endforeach</select></label><label>Approximate area<input name="area" value="{{ old('area') }}" placeholder="e.g. 2,000 m²" maxlength="100"></label><label class="wide">Site address *<textarea name="address" required maxlength="2000">{{ old('address') }}</textarea></label><label>Preferred visit date<input type="date" name="preferred_date" min="{{ today()->toDateString() }}" value="{{ old('preferred_date') }}"></label><label>Access details<textarea name="access_details" maxlength="3000" placeholder="Height, gate access, working hours or restrictions">{{ old('access_details') }}</textarea></label><label class="wide">Project requirements<textarea name="requirements" maxlength="3000">{{ old('requirements') }}</textarea></label></div>
<div class="trap" aria-hidden="true"><label>Leave blank<input name="website" tabindex="-1" autocomplete="off"></label></div>
<label class="check"><input type="checkbox" name="consent" value="1" required @checked(old('consent'))> I agree that BRON may use these details to respond to my enquiry and arrange the site visit.</label><p class="muted">Your details are available to BRON’s authorised staff. Contact hello@bronhighworks.com for questions about this enquiry.</p><button>Submit assessment request ↗</button></form>@endif
@endsection