<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $document->number }}</title></head>
<body style="margin:0;background:#f2f3ef;color:#242627;font-family:Arial,sans-serif">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f2f3ef;padding:24px 12px"><tr><td align="center">
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:720px;background:#fff;border-collapse:collapse">
<tr><td style="background:linear-gradient(90deg,#cbdd29 0%,#cbdd29 58%,#fff 100%);padding:24px 32px"><strong style="font-size:25px;letter-spacing:1px">BRON HIGHWORKS</strong></td></tr>
<tr><td style="padding:32px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td valign="top"><p style="margin-top:0">316-B, Lorong Kedah, Taman Melawati,<br>53100 Kuala Lumpur, Malaysia<br>hello@bronhighworks.com · +60 19-652 2238</p></td><td valign="top" align="right"><h1 style="font-size:23px;margin:0 0 6px">{{ \App\Models\BusinessDocument::TYPES[$document->type] }}</h1><strong>{{ $document->number }}</strong><p>{{ strtoupper(str_replace('_', ' ', $document->status)) }}<br>{{ $document->issued_on->format('d M Y') }}@if($document->due_on)<br>{{ $document->type === 'quotation' ? 'Valid until' : 'Due / delivery' }}: {{ $document->due_on->format('d M Y') }}@endif</p></td></tr></table>
<hr style="border:0;border-top:1px solid #ddd;margin:20px 0"><p style="font-size:11px;font-weight:bold;letter-spacing:1px;color:#687300">{{ $document->type === 'supplier_po' ? 'SUPPLIER' : 'CUSTOMER' }}</p><h2 style="font-size:18px;margin-bottom:4px">{{ $document->party_name }}</h2><p style="white-space:pre-line;margin-top:0">{{ $document->party_address }}</p>
<table role="presentation" width="100%" cellspacing="0" cellpadding="10" style="border-collapse:collapse;margin-top:24px"><thead><tr style="background:#242627;color:#fff"><th align="left">Description</th><th align="right">Qty</th>@if($document->type !== 'delivery_order')<th align="right">Unit price</th><th align="right">Amount (MYR)</th>@endif</tr></thead><tbody>@foreach($document->items as $item)<tr><td style="border-bottom:1px solid #ddd">{{ $item['description'] }}</td><td align="right" style="border-bottom:1px solid #ddd">{{ $item['quantity'] }}</td>@if($document->type !== 'delivery_order')<td align="right" style="border-bottom:1px solid #ddd">{{ number_format((float) $item['unit_price'], 2) }}</td><td align="right" style="border-bottom:1px solid #ddd">{{ number_format($item['total_cents'] / 100, 2) }}</td>@endif</tr>@endforeach</tbody></table>
@if($document->type !== 'delivery_order')<table role="presentation" align="right" cellspacing="0" cellpadding="5" style="margin-top:20px;min-width:260px"><tr><td>Subtotal</td><td align="right">{{ number_format($document->subtotal_cents / 100, 2) }}</td></tr><tr><td>Tax ({{ number_format($document->tax_basis_points / 100, 2) }}%)</td><td align="right">{{ number_format($document->tax_cents / 100, 2) }}</td></tr><tr><td><strong>Total MYR</strong></td><td align="right"><strong>{{ number_format($document->total_cents / 100, 2) }}</strong></td></tr>@if($document->type === 'invoice' && ! ($document->status === 'paid' && $document->payments->isEmpty()))<tr><td>Amount paid</td><td align="right">{{ number_format($document->recordedPaidCents() / 100, 2) }}</td></tr><tr><td><strong>Balance due</strong></td><td align="right"><strong>{{ number_format($document->balanceCents() / 100, 2) }}</strong></td></tr>@endif</table><div style="clear:both"></div>@endif
@if($document->notes)<h2 style="font-size:17px;margin-top:28px">Notes / terms</h2><p style="white-space:pre-line">{{ $document->notes }}</p>@endif
<p style="margin-top:30px">Please reply to this email if you have questions about this document.</p></td></tr>
<tr><td style="padding:20px 32px;background:#242627;color:#f5f5f1;font-size:12px">BRON Highworks · When the dirt’s too high, send BRON.</td></tr>
</table></td></tr></table>
</body></html>
